[package]
name = "bundlecat"
version = "0.2.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.38", features = ["derive"] }
ud3tn-aap = { git = "https://github.com/archipel-network/rust-ud3tn.git", version = "1.0.0" }
uuid = { version = "1.16.0", features = ["v4"] }
